"""Python bindings for ExcelReader."""

from excelreader.arrow_stream import ArrowStream
from excelreader.reader import Sheet, Workbook, decode_cell, open_bytes, open_workbook
from excelreader.types import (
    Cell,
    CellType,
    ColumnarSheet,
    ColumnSpec,
    ColumnType,
    ExcelReaderError,
    OpenOptions,
    PasswordIncorrectError,
    PasswordRequiredError,
    SheetVisibility,
    StringColumn,
    TypedTable,
    WriteOptions,
)
from excelreader.writer import (
    encrypt_package,
    encrypt_package_bytes,
    write_arrow,
    write_arrow_to_bytes,
    write_pandas,
    write_pandas_to_bytes,
    write_polars,
    write_polars_to_bytes,
    write_workbook,
    write_workbook_to_bytes,
)
from excelreader.writer_handle import SheetWriter, open_writer, open_writer_to_memory

__all__ = [
    "ArrowStream",
    "Cell",
    "CellType",
    "ColumnSpec",
    "ColumnType",
    "ColumnarSheet",
    "ExcelReaderError",
    "OpenOptions",
    "PasswordIncorrectError",
    "PasswordRequiredError",
    "Sheet",
    "SheetVisibility",
    "SheetWriter",
    "StringColumn",
    "TypedTable",
    "Workbook",
    "WriteOptions",
    "decode_cell",
    "encrypt_package",
    "encrypt_package_bytes",
    "open_bytes",
    "open_workbook",
    "open_writer",
    "open_writer_to_memory",
    "write_arrow",
    "write_arrow_to_bytes",
    "write_pandas",
    "write_pandas_to_bytes",
    "write_polars",
    "write_polars_to_bytes",
    "write_workbook",
    "write_workbook_to_bytes",
]
