//! `#[derive(ExcelMapper)]` for excelreader's `ExcelMapper` trait. Do not depend on this crate
//! directly - `excelreader` re-exports the macro from `excelreader::workbook::ExcelMapper`
//! (same identifier as the trait; derive macros and traits occupy different namespaces, so
//! there's no collision, same as `serde`/`serde_derive`).

use proc_macro::TokenStream;
use quote::quote;
use syn::spanned::Spanned;
use syn::{
    parse_macro_input, Data, DeriveInput, Field, Fields, GenericArgument, LitStr, PathArguments,
    Type,
};

#[proc_macro_derive(ExcelMapper, attributes(excel))]
pub fn derive_excel_mapper(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    expand(input)
        .unwrap_or_else(|e| e.to_compile_error())
        .into()
}

fn expand(input: DeriveInput) -> syn::Result<proc_macro2::TokenStream> {
    let struct_name = &input.ident;
    let fields = named_fields(&input)?;

    // Parsed ONCE, up front: both halves below read the same ParsedField, so they cannot disagree
    // about a field's kind, its primary name, or whether it is optional. Every attribute and type
    // error surfaces here, before either half is generated.
    let parsed = fields
        .iter()
        .map(parse_field)
        .collect::<syn::Result<Vec<_>>>()?;

    let bindings = parsed.iter().map(field_binding).collect::<Vec<_>>();

    // The write half needs one set of buffer identifiers per field, so it is generated by index
    // rather than field by field: the declarations, the per-row pushes, and the OwnedColumn
    // construction all have to agree on the same names.
    let mut declarations = Vec::new();
    let mut pushes = Vec::new();
    let mut columns = Vec::new();
    for (index, field) in parsed.iter().enumerate() {
        let plan = WriteField::new(index, field);
        declarations.push(plan.declarations());
        pushes.push(plan.push());
        columns.push(plan.column());
    }

    Ok(quote! {
        impl ::excelreader::workbook::ExcelMapper for #struct_name {
            fn bindings() -> ::std::vec::Vec<::excelreader::workbook::ColumnBinding<Self>> {
                ::std::vec![ #(#bindings),* ]
            }
        }

        impl ::excelreader::writer::ExcelWriter for #struct_name {
            fn to_columns(
                rows: &[Self],
            ) -> ::core::result::Result<
                ::std::vec::Vec<::excelreader::writer::OwnedColumn>,
                ::excelreader::Error,
            > {
                let n = rows.len();
                #(#declarations)*
                // ONE pass over the rows. Every field's append is monomorphic and inlined - there
                // is no per-cell match, no boxed closure, and no trait object anywhere in here.
                for (row, r) in rows.iter().enumerate() {
                    let _ = row; // unused when no field is Option<_>
                    #(#pushes)*
                }
                ::core::result::Result::Ok(::std::vec![ #(#columns),* ])
            }
        }
    })
}

fn named_fields(
    input: &DeriveInput,
) -> syn::Result<&syn::punctuated::Punctuated<Field, syn::Token![,]>> {
    // One pattern, one message: a tuple struct, a unit struct and an enum are all the same rejection,
    // and writing it twice is how the two copies eventually stop matching.
    if let Data::Struct(syn::DataStruct {
        fields: Fields::Named(fields),
        ..
    }) = &input.data
    {
        return Ok(&fields.named);
    }
    Err(syn::Error::new_spanned(
        input,
        "ExcelMapper can only be derived for structs with named fields",
    ))
}

/// Everything both halves of the derive need from one field, resolved once.
///
/// The read half (`field_binding`) and the write half (`WriteField`) used to each re-run
/// `excel_names`/`unwrap_option`/`FieldKind::from_type` over the same field. Parsing once is not
/// just less work: it is what guarantees the two halves cannot disagree about a field's kind or
/// about which of its names is the primary one.
struct ParsedField<'a> {
    ident: &'a syn::Ident,
    /// Primary `#[excel(name = "...")]` first, then any aliases in declared order.
    names: Vec<LitStr>,
    kind: FieldKind,
    is_option: bool,
}

fn parse_field(field: &Field) -> syn::Result<ParsedField<'_>> {
    let (inner_ty, is_option) = unwrap_option(&field.ty);
    Ok(ParsedField {
        ident: field.ident.as_ref().expect("named_fields guarantees Some"),
        names: excel_names(field)?,
        kind: FieldKind::from_type(inner_ty)?,
        is_option,
    })
}

fn field_binding(parsed: &ParsedField<'_>) -> proc_macro2::TokenStream {
    let field_ident = parsed.ident;
    let name = &parsed.names;
    let xl_type = parsed.kind.xl_type_tokens();
    let value = parsed.kind.value_tokens();
    let assign_value = if parsed.is_option {
        quote! { ::std::option::Option::Some(#value) }
    } else {
        value
    };

    quote! {
        ::excelreader::workbook::ColumnBinding {
            names: &[#(#name),*],
            xl_type: #xl_type,
            assign: |r, col, row| r.#field_ident = #assign_value,
        }
    }
}

fn excel_names(field: &Field) -> syn::Result<Vec<LitStr>> {
    let mut name = None;
    let mut aliases = Vec::new();
    for attr in &field.attrs {
        if !attr.path().is_ident("excel") {
            continue;
        }
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("name") {
                name = Some(meta.value()?.parse::<LitStr>()?);
                return Ok(());
            }
            if meta.path.is_ident("alias") {
                aliases.push(meta.value()?.parse::<LitStr>()?);
                return Ok(());
            }
            Err(meta.error("unsupported #[excel(...)] key, expected `name` or `alias`"))
        })?;
    }
    let Some(name) = name else {
        return Err(syn::Error::new(
            field.span(),
            "field is missing #[excel(name = \"...\")]",
        ));
    };
    let mut names = vec![name];
    names.extend(aliases);
    Ok(names)
}

/// Returns `(T, true)` for a field typed `Option<T>`, `(ty, false)` for anything else.
fn unwrap_option(ty: &Type) -> (&Type, bool) {
    let Type::Path(type_path) = ty else {
        return (ty, false);
    };
    let Some(segment) = type_path.path.segments.last() else {
        return (ty, false);
    };
    if segment.ident != "Option" {
        return (ty, false);
    }
    let PathArguments::AngleBracketed(args) = &segment.arguments else {
        return (ty, false);
    };
    if let Some(GenericArgument::Type(inner)) = args.args.first() {
        return (inner, true);
    }
    (ty, false)
}

#[derive(Clone, Copy)]
enum FieldKind {
    Str,
    /// `i64` itself, and every other integer width. The column is always `XL_T_I64` on the wire; a
    /// narrower field converts through `TryFrom` (see `value_tokens`).
    Int,
    /// `f64` itself, plus `f32`. The column is always `XL_T_F64` on the wire.
    Float,
    Bool,
    Date,
    Time,
    Timestamp,
}

struct WriteField {
    ident: syn::Ident,
    /// The PRIMARY #[excel(name = "...")] only. An alias must never reach a write spec: the ABI
    /// rejects a write spec carrying more than one name.
    name: LitStr,
    kind: FieldKind,
    is_option: bool,
    values: syn::Ident,
    offsets: syn::Ident,
    data: syn::Ident,
    validity: syn::Ident,
}

impl WriteField {
    fn new(index: usize, parsed: &ParsedField<'_>) -> WriteField {
        WriteField {
            ident: parsed.ident.clone(),
            name: parsed
                .names
                .first()
                .expect("excel_names always returns the primary name first")
                .clone(),
            kind: parsed.kind,
            is_option: parsed.is_option,
            values: quote::format_ident!("values_{index}"),
            offsets: quote::format_ident!("offsets_{index}"),
            data: quote::format_ident!("data_{index}"),
            validity: quote::format_ident!("validity_{index}"),
        }
    }

    fn declarations(&self) -> proc_macro2::TokenStream {
        let (values, offsets, data, validity) =
            (&self.values, &self.offsets, &self.data, &self.validity);
        let buffers = if matches!(self.kind, FieldKind::Str) {
            quote! {
                let mut #offsets: ::std::vec::Vec<i32> = ::std::vec::Vec::with_capacity(n + 1);
                #offsets.push(0);
                let mut #data: ::std::vec::Vec<u8> = ::std::vec::Vec::new();
            }
        } else {
            let element = self.kind.element_type();
            quote! {
                let mut #values: ::std::vec::Vec<#element> = ::std::vec::Vec::with_capacity(n);
            }
        };
        if !self.is_option {
            return buffers;
        }
        // ponytail: the bitmap is materialized for every Option<_> field, even one where no row
        // turns out to be None - n/8 bytes spent for nothing in that case. Tracking a `saw_none`
        // flag and passing None instead would reclaim them; not worth the branch until a profile
        // says otherwise.
        quote! {
            #buffers
            let mut #validity: ::std::vec::Vec<u8> = ::std::vec![0u8; n.div_ceil(8)];
        }
    }

    fn push(&self) -> proc_macro2::TokenStream {
        let ident = &self.ident;
        let append = self.append_tokens();
        let placeholder = self.placeholder_tokens();
        if !self.is_option {
            return quote! {
                {
                    let value = &r.#ident;
                    #append
                }
            };
        }
        let validity = &self.validity;
        quote! {
            match &r.#ident {
                ::core::option::Option::Some(value) => {
                    ::excelreader::writer::set_valid(&mut #validity, row);
                    #append
                }
                ::core::option::Option::None => { #placeholder }
            }
        }
    }

    /// Appends `value: &Inner` to this field's buffers. The conversions are the exact inverses of
    /// `FieldKind::value_tokens` on the read side - if one gains a type, so must the other.
    fn append_tokens(&self) -> proc_macro2::TokenStream {
        let (values, offsets, data) = (&self.values, &self.offsets, &self.data);
        let field = self.name.value();
        match self.kind {
            FieldKind::Str => quote! {
                ::excelreader::writer::push_str(&mut #offsets, &mut #data, value.as_str())?;
            },
            // Through TryFrom, not `as`, for the same reason the read side does: an `as` cast
            // would silently wrap a u64 that does not fit an i64 column, and a writer that quietly
            // changes the number it was given is worse than one that stops.
            FieldKind::Int => quote! {
                #values.push(
                    i64::try_from(*value).map_err(|_| ::excelreader::Error {
                        code: ::excelreader::XL_INVALID_ARGUMENT,
                        message: ::std::format!(
                            "field `{}` holds a value that does not fit an i64 column",
                            #field
                        ),
                    })?,
                );
            },
            FieldKind::Float => quote! { #values.push(f64::from(*value)); },
            FieldKind::Bool => quote! { #values.push(u8::from(*value)); },
            FieldKind::Date => quote! {
                #values.push(
                    ::core::convert::Into::<::excelreader::Date>::into(*value).days_since_epoch,
                );
            },
            FieldKind::Time => quote! {
                #values.push(
                    ::core::convert::Into::<::excelreader::Time>::into(*value).micros_since_midnight,
                );
            },
            FieldKind::Timestamp => quote! {
                #values.push(
                    ::core::convert::Into::<::excelreader::Timestamp>::into(*value).micros_since_epoch,
                );
            },
        }
    }

    /// A null row still occupies a slot in the values buffer; its cleared validity bit is what
    /// marks it absent. Zero (or the empty string) is the placeholder the writer never reads.
    fn placeholder_tokens(&self) -> proc_macro2::TokenStream {
        let (values, offsets, data) = (&self.values, &self.offsets, &self.data);
        if matches!(self.kind, FieldKind::Str) {
            return quote! { ::excelreader::writer::push_str(&mut #offsets, &mut #data, "")?; };
        }
        quote! { #values.push(::core::default::Default::default()); }
    }

    fn column(&self) -> proc_macro2::TokenStream {
        let (values, offsets, data, validity) =
            (&self.values, &self.offsets, &self.data, &self.validity);
        let name = &self.name;
        let payload = match self.kind {
            FieldKind::Str => quote! {
                ::excelreader::writer::OwnedColumnData::Str { offsets: #offsets, data: #data }
            },
            FieldKind::Int => quote! { ::excelreader::writer::OwnedColumnData::I64(#values) },
            FieldKind::Float => quote! { ::excelreader::writer::OwnedColumnData::F64(#values) },
            FieldKind::Bool => quote! { ::excelreader::writer::OwnedColumnData::Bool(#values) },
            FieldKind::Date => quote! { ::excelreader::writer::OwnedColumnData::Date(#values) },
            FieldKind::Time => quote! { ::excelreader::writer::OwnedColumnData::Time(#values) },
            FieldKind::Timestamp => {
                quote! { ::excelreader::writer::OwnedColumnData::Timestamp(#values) }
            }
        };
        let validity_expr = if self.is_option {
            quote! { ::core::option::Option::Some(#validity) }
        } else {
            quote! { ::core::option::Option::None }
        };
        quote! {
            ::excelreader::writer::OwnedColumn {
                name: ::core::option::Option::Some(#name),
                data: #payload,
                validity: #validity_expr,
            }
        }
    }
}

/// Every integer type that maps onto an `XL_T_I64` column. `i64` is included so the conversion in
/// `value_tokens` stays uniform - `TryFrom<i64> for i64` exists via the blanket `From` impl and
/// compiles away to nothing.
const INT_TYPES: &[&str] = &[
    "i8", "i16", "i32", "i64", "isize", "u8", "u16", "u32", "u64", "usize",
];

impl FieldKind {
    fn from_type(ty: &Type) -> syn::Result<FieldKind> {
        let name = match ty {
            Type::Path(type_path) => type_path
                .path
                .segments
                .last()
                .map(|segment| segment.ident.to_string()),
            _ => None,
        };
        match name.as_deref() {
            Some(int) if INT_TYPES.contains(&int) => Ok(FieldKind::Int),
            Some("String") => Ok(FieldKind::Str),
            Some("f32" | "f64") => Ok(FieldKind::Float),
            Some("bool") => Ok(FieldKind::Bool),
            // The `Naive*` names are chrono's, reached through the `excelreader/chrono` feature's
            // `From` impls. Matching on the type's last path segment means `chrono::NaiveDate`, a
            // `use`d `NaiveDate`, and an alias to either all resolve the same way - and if the
            // feature is off, the generated `.into()` fails to compile with the missing `From` impl
            // named, which points straight at the fix.
            Some("Date" | "NaiveDate") => Ok(FieldKind::Date),
            Some("Time" | "NaiveTime") => Ok(FieldKind::Time),
            Some("Timestamp" | "NaiveDateTime") => Ok(FieldKind::Timestamp),
            _ => Err(syn::Error::new_spanned(
                ty,
                "unsupported field type for #[derive(ExcelMapper)] - supported types are String, \
                 bool, any integer (i8..i64/isize, u8..u64/usize), f32, f64, the temporal newtypes \
                 Date/Time/Timestamp (or chrono's NaiveDate/NaiveTime/NaiveDateTime with the \
                 `chrono` feature), and Option<...> of any of those",
            )),
        }
    }

    fn xl_type_tokens(&self) -> proc_macro2::TokenStream {
        match self {
            FieldKind::Str => quote! { ::excelreader::XL_T_STRING },
            FieldKind::Int => quote! { ::excelreader::XL_T_I64 },
            FieldKind::Float => quote! { ::excelreader::XL_T_F64 },
            FieldKind::Bool => quote! { ::excelreader::XL_T_BOOL },
            FieldKind::Date => quote! { ::excelreader::XL_T_DATE },
            FieldKind::Time => quote! { ::excelreader::XL_T_TIME },
            FieldKind::Timestamp => quote! { ::excelreader::XL_T_TIMESTAMP },
        }
    }

    fn value_tokens(&self) -> proc_macro2::TokenStream {
        match self {
            FieldKind::Str => quote! { ::excelreader::workbook::column_str(col, row).to_string() },
            // Through `TryFrom`, not `as`: an `as` cast would silently wrap a value that does not
            // fit the declared field (a 70000 in a `u16` column becoming 4464), and a parser that
            // quietly changes the number it read is worse than one that stops.
            FieldKind::Int => quote! {
                ::core::convert::TryFrom::try_from(::excelreader::workbook::column_i64(col, row))
                    .expect("value does not fit this field's integer type")
            },
            // `as` is the only available narrowing for f64 -> f32, and it saturates to infinity
            // rather than wrapping, so there is no silent-corruption case to guard here.
            FieldKind::Float => quote! { ::excelreader::workbook::column_f64(col, row) as _ },
            FieldKind::Bool => quote! { ::excelreader::workbook::column_bool(col, row) },
            FieldKind::Date => {
                quote! { ::core::convert::Into::into(::excelreader::workbook::column_date(col, row)) }
            }
            FieldKind::Time => {
                quote! { ::core::convert::Into::into(::excelreader::workbook::column_time(col, row)) }
            }
            FieldKind::Timestamp => {
                quote! { ::core::convert::Into::into(::excelreader::workbook::column_timestamp(col, row)) }
            }
        }
    }
    /// The Rust element type of this kind's output buffer, at the column type's exact wire width.
    fn element_type(&self) -> proc_macro2::TokenStream {
        match self {
            // Str has no single element type - it uses an offsets/data pair instead.
            FieldKind::Str => quote! { u8 },
            FieldKind::Int | FieldKind::Time | FieldKind::Timestamp => quote! { i64 },
            FieldKind::Float => quote! { f64 },
            FieldKind::Bool => quote! { u8 },
            FieldKind::Date => quote! { i32 },
        }
    }
}

#[cfg(test)]
mod tests {
    use super::expand;
    use syn::DeriveInput;

    fn expand_str(src: &str) -> syn::Result<String> {
        let input: DeriveInput = syn::parse_str(src).expect("test input must parse as an item");
        expand(input).map(|tokens| tokens.to_string())
    }

    #[test]
    fn generates_one_binding_per_field_with_inferred_types() {
        let output = expand_str(
            r#"
            struct Row {
                #[excel(name = "Nome")]
                nome: String,
                #[excel(name = "Idade")]
                idade: i64,
                #[excel(name = "Peso")]
                peso: f64,
                #[excel(name = "Ativo")]
                ativo: bool,
            }
            "#,
        )
        .expect("expand must succeed");

        assert!(output.contains("impl :: excelreader :: workbook :: ExcelMapper for Row"));
        assert!(output.contains("XL_T_STRING"));
        assert!(output.contains("XL_T_I64"));
        assert!(output.contains("XL_T_F64"));
        assert!(output.contains("XL_T_BOOL"));
        assert!(output.contains("\"Nome\""));
        assert!(output.contains("\"Idade\""));
        assert!(output.contains("\"Peso\""));
        assert!(output.contains("\"Ativo\""));
    }

    #[test]
    fn wraps_option_fields_in_some() {
        let output = expand_str(
            r#"
            struct Row {
                #[excel(name = "Ativo")]
                ativo: Option<bool>,
            }
            "#,
        )
        .expect("expand must succeed");

        assert!(output.contains("Option :: Some"));
        assert!(output.contains("XL_T_BOOL"));
    }

    #[test]
    fn errors_when_name_attribute_is_missing() {
        let err = expand_str(
            r#"
            struct Row {
                nome: String,
            }
            "#,
        )
        .expect_err("must fail: no #[excel(name = ...)]");

        assert!(err.to_string().contains("missing #[excel(name"));
    }

    #[test]
    fn errors_on_unsupported_field_type() {
        let err = expand_str(
            r#"
            struct Row {
                #[excel(name = "Nome")]
                nome: Vec<u8>,
            }
            "#,
        )
        .expect_err("must fail: Vec<u8> is not a supported type");

        assert!(err.to_string().contains("unsupported field type"));
    }

    #[test]
    fn maps_every_integer_width_onto_an_i64_column() {
        for ty in [
            "i8", "i16", "i32", "i64", "isize", "u8", "u16", "u32", "u64", "usize",
        ] {
            let output = expand_str(&format!(
                r#"struct Row {{ #[excel(name = "N")] n: {ty}, }}"#
            ))
            .unwrap_or_else(|e| panic!("{ty} must be supported: {e}"));

            assert!(output.contains("XL_T_I64"), "{ty} must use XL_T_I64");
            // Narrowing goes through TryFrom, never a silent `as` cast.
            assert!(output.contains("try_from"), "{ty} must convert via TryFrom");
        }
    }

    #[test]
    fn maps_both_float_widths_onto_an_f64_column() {
        for ty in ["f32", "f64"] {
            let output = expand_str(&format!(
                r#"struct Row {{ #[excel(name = "V")] v: {ty}, }}"#
            ))
            .unwrap_or_else(|e| panic!("{ty} must be supported: {e}"));
            assert!(output.contains("XL_T_F64"), "{ty} must use XL_T_F64");
        }
    }

    #[test]
    fn maps_temporal_types_onto_their_own_column_types() {
        for (ty, expected) in [
            ("Date", "XL_T_DATE"),
            ("NaiveDate", "XL_T_DATE"),
            ("Time", "XL_T_TIME"),
            ("NaiveTime", "XL_T_TIME"),
            ("Timestamp", "XL_T_TIMESTAMP"),
            ("NaiveDateTime", "XL_T_TIMESTAMP"),
        ] {
            let output = expand_str(&format!(
                r#"struct Row {{ #[excel(name = "D")] d: {ty}, }}"#
            ))
            .unwrap_or_else(|e| panic!("{ty} must be supported: {e}"));
            assert!(output.contains(expected), "{ty} must use {expected}");
        }
    }

    #[test]
    fn resolves_temporal_types_through_a_qualified_path() {
        let output = expand_str(
            r#"
            struct Row {
                #[excel(name = "D")]
                d: chrono::NaiveDate,
            }
            "#,
        )
        .expect("a qualified path must resolve by its last segment");

        assert!(output.contains("XL_T_DATE"));
    }

    #[test]
    fn errors_on_non_struct_input() {
        let err = expand_str(
            r#"
            enum Row {
                A,
            }
            "#,
        )
        .expect_err("must fail: enum is not a struct");

        assert!(err
            .to_string()
            .contains("can only be derived for structs with named fields"));
    }
    #[test]
    fn collects_aliases_in_declared_order_after_the_primary_name() {
        let output = expand_str(
            r#"
        struct Row {
            #[excel(name = "Nome", alias = "Nom", alias = "Name")]
            nome: String,
        }
        "#,
        )
        .expect("expand must succeed");

        let nome_pos = output.find("\"Nome\"").expect("primary name must appear");
        let nom_pos = output.find("\"Nom\"").expect("first alias must appear");
        let name_pos = output.rfind("\"Name\"").expect("second alias must appear");
        assert!(nome_pos < nom_pos, "primary name must precede its aliases");
        assert!(nom_pos < name_pos, "aliases must stay in declared order");
    }
    #[test]
    fn generates_an_excel_writer_impl_alongside_the_mapper() {
        let output = expand_str(
            r#"
            struct Row {
                #[excel(name = "Nome", alias = "Name")]
                nome: String,
                #[excel(name = "Peso")]
                peso: Option<f64>,
            }
            "#,
        )
        .expect("expand must succeed");

        assert!(output.contains("impl :: excelreader :: writer :: ExcelWriter for Row"));
        assert!(
            output.contains("push_str"),
            "a String field must go through push_str"
        );
        assert!(
            output.contains("set_valid"),
            "an Option field must set a validity bit"
        );
        // The alias belongs to the read side only: a write spec carrying two names is rejected by
        // the ABI.
        let writer_half = output
            .split("ExcelWriter for Row")
            .nth(1)
            .expect("the writer impl must be present");
        assert!(
            !writer_half.contains("\"Name\""),
            "an alias must never reach a write column"
        );
        assert!(
            writer_half.contains("\"Nome\""),
            "the primary name must reach the write column"
        );
    }
}
